In [2]:

pip install pandas

Requirement already satisfied: pandas in g:\depi\giz4_ais2_ml\.env\lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in g:\depi\giz4_ais2_ml\.env\lib\site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in g:\depi\giz4_ais2_ml\.env\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in g:\depi\giz4_ais2_ml\.env\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in g:\depi\giz4_ais2_ml\.env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

s=pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [3]:
s = pd.Series([1,2,3,4] ,index =["a" ,"b" ,"c" ,"d"])
s

a    1
b    2
c    3
d    4
dtype: int64

In [12]:
data = [[1,444,"abc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,444,"xyz"]]
df = pd.DataFrame(data,columns= ['id' ,'salary','dept'])
display(df)
x = df.columns
index =['r1' ,'r2' ,'r3' ,'r4']
df.index =index
df

   id  salary dept
0   1     444  abc
1   2     555  def
2   3     666  ghi
3   4     444  xyz

    id  salary dept
r1   1     444  abc
r2   2     555  def
r3   3     666  ghi
r4   4     444  xyz

In [14]:
df.dtypes

id        int64
salary    int64
dept        str
dtype: object

In [ ]:
df['dept'].dtype

In [18]:
def chk(df ,ty):
    return df[ty].dtype
chk(df ,'salary')

dtype('int64')

In [22]:
df['dept'] =df['dept'].astype('category')
df.dtypes

id           int64
salary       int64
dept      category
dtype: object

In [24]:
df['salary'].nunique()

3

In [25]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, r1 to r4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      4 non-null      int64
 1   salary  4 non-null      int64
 2   dept    4 non-null      category
dtypes: category(1), int64(2)
memory usage: 304.0+ bytes

In [27]:
df['salary'].values

array([444, 555, 666, 444])

In [28]:
df.replace(555,'ali' )

    id salary dept
r1   1    444  abc
r2   2    ali  def
r3   3    666  ghi
r4   4    444  xyz

In [33]:
header_col =['index' , 'gender','dept','postal_cod']
data =pd.read_table('http://bit.ly/movieusers%27', sep ='|', header =None,names =header_col)
data

     index gender           dept postal_cod
1       24      M     technician      85711
2       53      F          other      94043
3       23      M         writer      32067
4       24      M     technician      43537
5       33      F          other      15213
..     ...    ...            ...        ...
939     26      F        student      33319
940     32      M  administrator      02215
941     20      M        student      97229
942     48      F      librarian      78209
943     22      M        student      77841

[943 rows x 4 columns]

In [36]:
data = pd.read_csv('http://bit.ly/uforeports')
data

,City,Colors Reported,Shape Reported,State,Time
0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00
1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00
2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00
3,Abilene,NaN,DISK,KS,6/1/1931 13:00
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00
...,...,...,...,...,...
18236,Grant Park,NaN,TRIANGLE,IL,12/31/2000 23:00
18237,Spirit Lake,NaN,DISK,IA,12/31/2000 23:00
18238,Eagle River,NaN,NaN,WI,12/31/2000 23:45
18239,Eagle River,RED,LIGHT,WI,12/31/2000 23:45
18240,Ybor,NaN,OVAL,FL,12/31/2000 23:59

In [39]:
data.shape

(18241, 5)

In [41]:
data['Location'] = data.City +' '+data.State
data

,City,Colors Reported,Shape Reported,State,Time,Location
0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,Ithaca NY
1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,Willingboro NJ
2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,Holyoke CO
3,Abilene,NaN,DISK,KS,6/1/1931 13:00,Abilene KS
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,New York Worlds Fair NY
...,...,...,...,...,...,...
18236,Grant Park,NaN,TRIANGLE,IL,12/31/2000 23:00,Grant Park IL
18237,Spirit Lake,NaN,DISK,IA,12/31/2000 23:00,Spirit Lake IA
18238,Eagle River,NaN,NaN,WI,12/31/2000 23:45,Eagle River WI
18239,Eagle River,RED,LIGHT,WI,12/31/2000 23:45,Eagle River WI
18240,Ybor,NaN,OVAL,FL,12/31/2000 23:59,Ybor FL

In [42]:
data.to_csv('test.csv')

In [43]:
data.columns = data.columns.str.replace(" ",'_')
data

,City,Colors_Reported,Shape_Reported,State,Time,Location
0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,Ithaca NY
1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,Willingboro NJ
2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,Holyoke CO
3,Abilene,NaN,DISK,KS,6/1/1931 13:00,Abilene KS
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,New York Worlds Fair NY
...,...,...,...,...,...,...
18236,Grant Park,NaN,TRIANGLE,IL,12/31/2000 23:00,Grant Park IL
18237,Spirit Lake,NaN,DISK,IA,12/31/2000 23:00,Spirit Lake IA
18238,Eagle River,NaN,NaN,WI,12/31/2000 23:45,Eagle River WI
18239,Eagle River,RED,LIGHT,WI,12/31/2000 23:45,Eagle River WI
18240,Ybor,NaN,OVAL,FL,12/31/2000 23:59,Ybor FL